# Generated by Django 4.1 on 2022-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0025_sku_unic_alter_bakeries_options_alter_bakeries_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unic_code',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='unic_code',
            name='unic',
        ),
        migrations.AlterModelOptions(
            name='bakeries',
            options={'verbose_name_plural': 'Bakeries'},
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=966),
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.DeleteModel(
            name='Unic',
        ),
        migrations.DeleteModel(
            name='Unic_code',
        ),
    ]
